/** Random lobby nicknames drawn from deck punchlines / proper names. */
export const NICKNAME_POOL: string[] = [
  "los gays",
  "mear a alguien porque te lo pide",
  "mi abuela agonizando",
  "fractura de fémur",
  "una paja mal hecha",
  "fiesta privada en el baño",
  "despertarte inspirado",
  "hacer que me corra muy rápido",
  "hackeo cuántico",
  "arrastrarte",
  "mover el paquete",
  "dermovagisil",
  "ser rico",
  "nacer para ser un pagafantas",
  "encefalopatía espongiforme",
  "cantos gregorianos",
  "el Código de Hammurabi",
  "la CIA",
  "sexo con señoras muy gordas",
  "pan y circo",
  "echar lefa de gran calidad",
  "Satoshi Nakamoto",
  "ansiedad y depresión",
  "pedir justicia",
  "tu puto padre",
  "pasión por la comida",
  "cagar en aspersión",
  "mucha leche solidificada",
  "parálisis permanente",
  "un marroquí",
  "con la ayuda de Dios",
  "mi mamá encerrada en el baño",
  "promesas recicladas",
  "relaciones emocionales",
  "vergüenza ajena crónica",
  "colarme por la puerta trasera",
  "cadera dislocada",
  "mucho pelo en el culo",
  "comer comida callejera India",
  "Rayo McQueen",
  "un gol del Betis",
  "un pájaro de dos cabezas",
  "el clitoris",
  "el conflicto Israel-Palestina",
  "tener un novio israelí",
  "romper con la monotonía",
  "un extraterrestre disfrazado",
  "un grupo hacker coreano",
  "mi proctólogo favorito",
  "meterse un tiro",
  "la Gripe de Osaka",
  "el poder del tercer ojo",
  "jugar al Tetris",
  "la máquina Enigma",
  "Mr. Incognito",
  "atreverse a pensar diferente",
  "frases que no entendía",
  "el Defensor del Menor",
  "el mundo era nuestro",
  "el valor de decir “no”",
  "practicar la gratitud a diario",
  "el culo de Aitana",
  "brainstorming de ideas suicidas",
  "ser alquimista y fabricar oro",
  "tenerlo en la punta de lengua",
  "una nueva ETS",
  "el crack del 29",
  "antes la gente se mojaba",
  "ir cachondo todo el día",
  "un juego de rol",
  "un momento demente",
  "psilocibina",
  "perder la mitad de su valor",
  "League of Legends",
  "trabajar por placer",
  "mi colección de ETSs",
  "con mucha saliva",
  "partir un perro a la mitad",
  "quizás no esté tan mal",
  "porque estaba muy aburrido",
  "comerme el último trozo de pizza",
  "apretarlo hasta que reviente",
  "orgía de solidaridad",
  "un caso de exterminio familiar",
  "ir desnudo al Telepizza",
  "el suegro que critica tu trabajo",
  "alzamiento de penes",
  "espiar a la gente",
  "un club de BDSM",
  "xvideos",
  "mujeres meando juntas",
  "backdoor para optimizar tu vida",
  "el sindicato de trabajadores",
  "una milanesa",
  "salsa brava casera",
  "despacito y con buena letra",
  "una ciega",
  "Pablo Motos",
  "el proyecto nuclear de Irán",
  "morir",
  "deporte nocturno",
  "muchos años",
  "Mr.Anal",
  "invasión en Ceuta y Melilla",
  "se lo comió mi perro",
  "ayudarnos entre nosotros",
  "reconozco que me emociona",
  "puto el que lo lea",
  "sentir cómo cruje algo",
  "un montón de dinero en efectivo",
  "¡Mirá!",
  "sal de frutas",
  "una cabeza de la Isla de Pascua",
  "alguno habrá que le guste….",
  "rayos X",
  "una lluvia de meteoritos",
  "una vida sexual plena",
  "DMT: la partícula de Dios",
  "una indirecta muy directa",
  "romper tu corazón",
  "wi-fi",
  "pequeña y verrugosa",
  "cannabinoides sintéticos",
  "un nuevo color",
  "estar muy concentrado",
  "vivir en un contenedor de basura",
  "el ojo morado de mi novia",
  "cuy frito con arroz y papas",
  "envenenar los pozos",
  "¡Sí!",
  "quedar como follamigos",
  "haré que me escuchen",
  "una jornada muy dura",
  "está comprobado científicamente",
  "un recuerdo de mi infancia",
  "el Metro de Madrid",
  "Isla Fulana",
  "la sonrisa de un niño",
  "el final de Pedro Sánchez",
  "el nuevo Ayatolá",
  "la baliza V16",
  "un sistema para blanquear dinero",
  "que te revienten los dientes",
  "el analgésico supremo",
  "una célula terrorista",
  "tener el alma atrofiada",
  "globalizar el machismo",
  "tener cara de drogadicto",
  "el silencio como respuesta",
  "tus nalgas en mis mofletes",
  "la raza aria",
  "fumada absoluta",
  "el lugar más visitado del mundo",
  "adorar a Quezalcoatl",
  "riesgo biológico",
  "su plan va a funcionar",
  "decir que mi padre es polícia",
  "no llevar ropa interior",
  "acostarte con tu suegra",
  "el suero de la verdad",
  "un gesto que invita a más",
  "por encima de la media",
  "Francisco Franco",
  "la Casa de las Carcasas",
  "marcas en los brazos",
  "alcanzar el orgasmo rápidamente",
  "demencia senil",
  "convencer al electorado",
  "águila coja",
  "una misteriosa dama",
  "chaleco explosivo talla XS",
  "pelea de pokemons de nivel 1",
  "Síndrome Alcohólico Fetal",
  "tirarle la copa encima a alguien",
  "un funkopop de Chayanne",
  "Sasha Grey",
  "vaciar la nevera",
  "test civilizacional",
  "un negro marica",
  "podemos",
  "el logopeda de Bad Bunny",
  "la caída del régimen cubano",
  "microplásticos",
  "resucitar al tercer día",
  "muy silencioso",
  "pero era gracioso",
  "crucifixión",
  "morir de escorbuto",
  "vomitar en medio de una mamada",
  "liderar una exitosa banda",
  "tu ego asustado",
  "drogas de diseño para elefantes",
  "copiar y pegar",
  "el talento de las mujeres",
  "Juan Ramón Rallo",
  "los reptilianos",
  "bien poderoso",
  "empanadas rellenas de billetes",
  "una bola de pinchos",
  "más rápido que Fernando Alonso",
  "un control de alcoholemia",
  "hacer croquetas",
  "hacer un vídeo con Bruno y María",
  "una vida triste",
  "mucha testosterona",
  "otra oportunidad perdida",
  "25 centimetros",
  "una foto tuya en mi cartera",
  "un creciente malestar",
  "borrando datos",
  "un desafío no resuelto",
  "atribuible a un bot",
  "unas llagas en el pene",
  "comida a domicilio",
  "su jeringuilla “mágica”",
  "buscar algo que se te ha perdido",
  "dedos como pollas",
  "los campos de concentración",
  "la Virgen de los Dolores",
  "el amor no tiene edad",
  "conectar con tus ancestros",
  "mucha fricción",
  "comer mayonesa a cucharadas",
  "la tarjeta de El Hormiguero",
  "darle una hostia a un diputado",
  "una base militar alienígena",
  "jagermeister en vena",
  "vacío y muerto por dentro",
  "perro ladrador, poco mordedor",
  "el nuevo GTA",
  "música electrolatina",
  "no vas a creer lo que ví",
  "una smash burger",
  "borracho perdido",
  "manipular las estadísticas",
  "hacer el baile prohibido",
  "Comunismo Nazi",
  "altas tasas de suicidio juvenil",
  "camarón de la Isla",
  "segun mis calculos",
  "en el bar del chino franquista",
  "hacerlo a cámara lenta",
  "es buscarse la ruina",
  "un robot que baila salsa",
  "Dios",
  "acabar con la pobreza del mundo",
  "abstinencia",
  "demasiados estímulos",
  "chupar percebes",
  "envenenar a Vladimir Putin",
  "detonar a todos tus amigos",
  "cumplir al pie de la letra",
  "belleza peculiar",
  "mandar nudes a tu sobrino",
  "la mayor amenaza del siglo XXI",
  "un gran danés",
  "la Humanidad",
  "tu destreza sexual",
  "el Ché Guevara",
  "columbofilia",
  "estar vivo de milagro",
  "confirmado por la ciencia",
  "brutalidad policial merecida",
  "una bola de fuego",
  "cualquier cosa de Asia",
  "los misterios de Pekín",
  "8 horas en TikTok al día",
  "un chorrito de limoncito",
  "está controlado por los gitanos",
  "fauces pinchudas",
  "no volveré a tener sexo",
  "utopía",
  "Macarena",
  "una Yonki lata",
  "la dieta que no cumplirás",
  "una transfusión de heces",
  "descender al abismo",
  "donde hay confianza da asco",
  "Sarah Santaolalla",
  "el Rey Arturo con su espada",
  "depresión permanente",
  "residuos radiactivos en el río",
  "mi secretaria",
  "el lápiz más afilado del estuche",
  "el ingreso mínimo vital",
  "que te roben la dignidad",
  "frodo follándose a Gollum",
  "mi verdadero yo",
  "usar Ana como femenino de Ano",
  "dar el 200% de uno mismo",
  "meterme unas setas de rave",
  "no saber pedir disculpas",
  "unas siamesas",
  "todos tus seres queridos",
  "2 centímetros de polla",
  "el camino del héroe",
  "reorganizacion de órganos",
  "una pluma",
  "sexo matutino",
  "ver el atardecer con tu pareja",
  "mi mayor decepción sexual",
  "recibir estímulos constantes",
  "compartir jeringuilla",
  "confundir deseos con derechos",
  "Charocracia Ilustrada",
  "sentido común",
  "el flautista de Hamelín",
  "crema antiarrugas",
  "gravar a mis padres",
  "hijo de puta",
  "píldoras anticonceptivas",
  "responsabilidad histórica",
  "no me soporto",
  "la Transición Española",
  "alcoholismo",
  "20 años de revolución socialista",
  "amianto",
  "maquillaje para tapar moratones",
  "cristal",
  "el acabose",
  "embarazo psicológico la Matrix",
  "varios kilómetros de verga",
  "i-diotas con sus i-Phones",
  "una flor venenosa",
  "el color naranja de las nubes",
  "Pablo Escobar",
  "lavar la ropa a mano",
  "las peores condiciones de vida",
  "mezclar es fácil",
  "una vasectomía casera",
  "un club de juegos de mesa",
  "vencer al cáncer infantil",
  "una jovencita con un cuchillo",
  "la peste negra",
  "Carmen Lomama",
  "plenamente activo",
  "placer gratis",
  "escucharse a uno mismo",
  "Bob Marley",
  "llevar un pulpo como sobrero",
  "cuando me secuestró la Yakuza",
  "el afán competitivo",
  "un nazgul",
  "deficit de atención",
  "un acertijo sin resolución",
  "la guerra de las consolas",
  "entralazamiento cuántico",
  "hacer cosas nazis",
  "caridad con deducción fiscal",
  "un cuerpo para el delito",
  "gonorrea como forma de vida",
  "un cargamento de varitas mágicas",
  "obtener placer con un vegetal",
  "me gusta dejar buena impresión",
  "el segundo antes del Big Bang",
  "unos pechos mucho más turgentes",
  "una historia de superación",
  "tener uñas parras",
  "pérdidas de orina",
  "un influencer gastronómico",
  "desechos químicos",
  "es un contubernio judeomasónico",
  "mi historial de navegación",
  "herencia emocional no declarada",
  "negro, pero muy negro",
  "el video porno de Juana de Arco",
  "mamadas para todos",
  "dejarme violar",
  "el emoji de la berenjena",
  "juntos para siempre",
  "italianos",
  "el nuevo Hitler",
  "llevar un polo rosa",
  "una clase increíble",
  "el problema de la vivienda",
  "semen rojo",
  "que te explote un huevo",
  "dolor",
  "un gitano",
  "irme de putas con Ábalos y Koldo",
  "un tirón en la espalda",
  "mis partes íntimas",
  "la opción más votada",
  "una china muy flexible",
  "la paz mundial",
  "el Imperio del Silicio",
  "una bandeja de sushi y nigiris",
  "inter-gay-láctico",
  "hackeo de marcapasos",
  "esperma de ballena",
  "matar a alguien sin querer",
  "politraumatismo craneoencefálico",
  "ligadura de trompas",
  "toque de queda",
  "España va bien",
  "la mesa del salón",
  "una caca postiza",
  "huir haciendo la croqueta",
  "la última regla",
  "atropellar a una monja",
  "familia feliz",
  "el ruido de la cama del hostal",
  "asado humano a la parrila",
  "hacerse la interesante",
  "homicidio involuntario",
  "espiar el teléfono de mi pareja",
  "la economía de este maldito país",
  "deporte de alto riesgo",
  "avanzar hacia una nueva era",
  "por amor al juego",
  "una montaña de cabezas cortadas",
  "me gusta precisamente por eso",
  "beberte una lámpara de lava",
  "taxidermia a domicílio",
  "Bertin Osborne",
  "ropa interior comestible",
  "una prisión",
  "hacer una amistad para siempre",
  "problemas del primer mundo",
  "historia del país",
  "ser un cobarde",
  "ir vestido de negro",
  "el líder de la oposición",
  "un canario en la mina",
  "doble papada",
  "cocaína, magia y necrofília",
  "preservativos XXL",
  "la Fosa de las Marianas",
  "ir a un notario",
  "un chino muy malo en matemáticas",
  "porno japonés con tentáculos",
  "un hacker ruso",
  "transmitir bastante seguridad",
  "un accidente en la carretera",
  "un positivo en cannabis",
  "una víctima más",
  "muchas cosquillas",
  "los tecnoligarcas",
  "una tonelada de harina",
  "trípodes",
  "el Niño Jesús en el pesebre",
  "sudor genital radioactivo",
  "observar lo que tienes delante",
  "atajos para la felicidad",
  "San Valentín",
  "se fue todo el mundo",
  "escrache a un político",
  "servicio público",
  "tragarte lo impensable",
  "un espía",
];

/** "comida a domicilio" -> "ComidaADomicilio" (no spaces; caps instead). */
export function toCamelNick(raw: string): string {
  const cleaned = raw
    .normalize('NFC')
    .replace(/[“”"«»']/g, '')
    .replace(/[^0-9A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+/g, ' ')
    .trim();
  if (!cleaned) return 'Guerrilla';
  return cleaned
    .split(/\s+/)
    .filter(Boolean)
    .map((w) => {
      if (/^[A-ZÁÉÍÓÚÜÑ0-9]{2,}$/.test(w)) return w; // keep acronyms CIA, VOX
      const lower = w.toLocaleLowerCase('es-ES');
      return lower.charAt(0).toLocaleUpperCase('es-ES') + lower.slice(1);
    })
    .join('')
    .slice(0, 42);
}

export function randomNickname(exclude?: string): string {
  if (!NICKNAME_POOL.length) return 'Guerrilla';
  for (let i = 0; i < 16; i++) {
    const n = toCamelNick(NICKNAME_POOL[Math.floor(Math.random() * NICKNAME_POOL.length)]);
    if (!exclude || n.toLowerCase() !== exclude.toLowerCase()) return n;
  }
  return toCamelNick(NICKNAME_POOL[Math.floor(Math.random() * NICKNAME_POOL.length)]);
}
