import { useMemo } from 'react';
import { StyleSheet } from 'react-native';
import { useTheme } from '@/src/store/ThemeContext';

/** Styles for app/play.tsx (moved verbatim in v0.99.422.29). */
export function usePlayStyles() {
  const { colors, fontFamily } = useTheme();
  return useMemo(
    () =>
      StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  discardCounterBox: {
    backgroundColor: '#5A1820',
    borderWidth: 2,
    borderColor: '#E53935',
    borderRadius: 4,
    paddingVertical: 10,
    paddingHorizontal: 14,
    alignItems: 'center',
    gap: 2,
    marginBottom: 4,
  },
  discardCounterText: {
    color: '#FFCDD2',
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  discardCounterHint: {
    color: '#E57373',
    fontSize: 12,
    fontWeight: '600',
  },
  adminBar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingTop: 6,
    paddingBottom: 2,
  },
  adminChip: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bgElevated,
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  adminChipText: {
    color: colors.accentSoft,
    fontSize: 11,
    fontWeight: '800',
  },
  sticky: {

    paddingHorizontal: 10,
    paddingTop: 6,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.bg,
    gap: 4,
    zIndex: 20,
  },
  roundSticky: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  roundStickyTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '900',
    flexShrink: 1,
  },
  roundStickyScore: {
    color: colors.accentSoft,
    fontSize: 13,
    fontWeight: '900',
  },
  scrollInnerTight: {
    paddingTop: 8,
    gap: 8,
  },
  scroll: { flex: 1 },
  scrollInner: { padding: 16, paddingBottom: 48, gap: 12 },
  liveBox: {
    backgroundColor: colors.promptBg,
    borderRadius: 4,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 12,
    paddingRight: 16,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 4,
  },
  liveBoxWithFavSlot: {
    position: 'relative',
    // Keep right gutter reserved so ★ never pushes the prompt sideways
    paddingRight: 44,
  },
  liveLabel: {
    color: colors.accentSoft,
    fontWeight: '800',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  doneBox: {
    backgroundColor: colors.bgElevated,
    borderRadius: 4,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.accent,
    gap: 8,
  },
  doneBadge: {
    color: colors.accentSoft,
    fontWeight: '900',
    fontSize: 15,
  },
  scores: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  scoreItem: {
    color: colors.textMuted,
    backgroundColor: colors.bgElevated,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 3,
    overflow: 'hidden',
    fontWeight: '600',
  },
  seatRow: { gap: 8 },
  hand: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    justifyContent: 'flex-start',
    width: '100%',
  },
  handItem: {
    flexGrow: 0,
    flexShrink: 0,
  },
  revealFavStarAbs: {
    position: 'absolute',
    top: 4,
    right: 6,
    zIndex: 5,
  },
  revealFavStar: {
    color: colors.zar,
    fontSize: 28,
    fontWeight: '900',
    lineHeight: 32,
    paddingHorizontal: 4,
  },
  revealTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  revealActionRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 8,
    width: '100%',
  },
  shareSquare: {
    width: 52,
    height: 52,
    borderRadius: 4,
    borderWidth: 0,
    backgroundColor: '#2AABEE',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 1,
    paddingTop: 2,
  },
  shareEnviar: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.2,
    lineHeight: 10,
    textTransform: 'lowercase',
  },
  sharePlane: {
    fontSize: 24,
    color: colors.accentSoft,
    lineHeight: 28,
  },
  guardarFlex: {
    flex: 1,
    justifyContent: 'center',
  },
  soloCompactBlock: {
    gap: 8,
  },
  soloCompactBlockHidden: {
    opacity: 0,
  },
  soloMine: {
    backgroundColor: colors.promptBg,
    borderRadius: 4,
    paddingVertical: 8,
    paddingHorizontal: 10,
    gap: 4,
    borderWidth: 1.5,
    borderColor: colors.accent,
  },
  soloMineBadge: {
    color: colors.accentSoft,
    fontWeight: '900',
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  soloMineAnswers: {
    color: '#FF8A3D',
    fontWeight: '800',
    fontSize: 15,
    lineHeight: 20,
    textDecorationLine: 'underline',
  },
  soloSecondary: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  roundLastAnswer: {
    backgroundColor: colors.bgElevated,
    borderRadius: 4,
    paddingVertical: 12,
    paddingHorizontal: 12,
    gap: 10,
    borderWidth: 1,
    borderColor: colors.accent,
    marginTop: 8,
  },
  roundLastTitle: {
    color: colors.accentSoft,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  soloRival: {
    backgroundColor: colors.bgElevated,
    borderRadius: 3,
    paddingVertical: 6,
    paddingHorizontal: 8,
    gap: 2,
    borderWidth: 1,
    borderColor: colors.border,
  },
  soloMineRow: {
    borderColor: colors.accent,
    backgroundColor: colors.promptBg,
  },
  soloRivalHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  soloStar: {
    color: colors.zar,
    fontSize: 18,
    fontWeight: '900',
    paddingHorizontal: 4,
  },
  soloRivalText: {
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '600',
  },
  judgeCard: {
    backgroundColor: colors.bgElevated,
    borderRadius: 4,
    padding: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: colors.border,
    minHeight: 132,
  },
  judgeCardBody: {
    minHeight: 56,
    justifyContent: 'center',
  },
  judgeLabel: {
    color: colors.accentSoft,
    fontWeight: '800',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
}),
    [colors, fontFamily]
  );
}
